src/videojs.errors.js

This is a defensive coding measure to handle the odd/rare event that an error event is triggered but no error object is cached by the player. This has been witnessed with CORS errors in local dev; such as loading a poster image in Safari.

Error Defense

---

src/plugin.js
test/plugin.test.js

OnceUX playback was timing out during long pre rolls due to videojs-contrib-ads emitting 'adtimeupdate' events and not 'timeupdate' events. Since The videojs-errors plugin listens for 'timeupdate' events, playback was stalling. This fix monitors both 'timeupdate' and 'adtimeupdate' events.

Added listening for adtimeupdate

---

package.json
src/plugin.js
src/plugin.scss

**Issue Description:**
The issue is that we do not have a close-button but just a visual indicator 'X' to tell the user that there is a close button on the modal. 
**Fix Description:**
This fix removes the visual "X" indicator and replaces it with a close button which is also accessible as it has a control text associated with it. The idea behind showing up the close-button is that we have made the `errorDisplay` closeable.
Made some CSS changes so that the close button aligns with the `vjs-errors-dialog` top right edge always.
Attaching screenshots of how it looks across various player sizes.

Close-button errors message accessible fix

---

src/plugin.js
src/plugin.scss
test/plugin.test.js

**Problem Description** 
When trying to play the video in IE **_(when Flash has been disabled or not installed)_** , users presented with a `MEDIA_ERR_SRC_NOT_SUPPORTED` error along with the associated technical details
**Fix Details**
The technical details / description does not say anything about flash being disabled, so adding a description after the Flash enabled check has been made, will provide the user with a clue if there is no Flash installed or disabled in IE.
After the Fix the technical description should read this
>`ASSOCIATED_TECHNICAL_DESCRIPTION` + . You could also try installing Flash.
**Latest Changes in the fix proposed:**
We are going to add in the flash message after the technical description instead of appending it as stated above in fix details.

Add in a user-friendly message for disabled Flash in IE

---

src/plugin.js
test/plugin.test.js

Plugin now cleans up event bindings when it is reinitialized.
Healthcheck continues to run even when the player has paused or ended and resets the timeout monitor in these cases instead of just unbinding healthcheck. In a live case, since duration must manually be updated as we get more segments, the dom element may report that it has `ended` when it really hasnt yet since it cant know about our abstraction.

Cleanup event bindings when reinitialized

---

README.md
lang/en.json
src/js/index.js
test/index.test.js

This adds three new custom errors to match the possible errors returned [from the Brightcove Playback API with a 403](https://docs.brightcove.com/en/video-cloud/playback-api/references/error-reference.html).
While I'd usually be hesitant to implement something so specific to Brightcove, the concepts of domain, IP, and geo restriction are not unique to us and may be useful for others.

feat: Add new custom errors and allow defining custom errors at runtime

---

src/js/index.js

This was previously detecting a "small" player by using the `width` and `height` methods. The newer `currentWidth` and `currentHeight` are more reliable for this use-case.

Fix size detection to account for players that have no configured dimensions.

---

src/js/index.js
test/index.test.js

This PR adds a flag to disable watching the `progress` event. The reason for this is that `progress` coming from the video element doesn't really mean anything when using MSE. 
Added `player.errors.disableProgress()` to disable watching `progress` events. Defaults to `false`.

Added option to disable watching progress

---

README.md
index.html
src/plugin.js
test/plugin.test.js

BREAKING CHANGE: Changed the codes of recently-added errors; so, they will work with 1.x implementations.

Change codes of recently-added errors and allow type and code to be shared.

---

src/plugin.js
test/plugin.test.js

Currently the player relies on the tech to trigger `waiting` and show the spinner, however it looks like `waiting` is followed by a `timeupdate` which causes the spinner to be cleared. 
This change will cause a spinner to show if the player hasn't made progress for 1 second regardless of whatever the tech does.

fix: show spinner if player has stalled

---

src/plugin.js

The redispatch change in contrib-ads v5.0 means that all player events are redispatched during ad playback. In this case, this meant that some users would not see error dialog contents during ad playback if there was an error on the player. This addresses that situation by listening for both the `aderror` redispatch-prefixed event and the regular `error` event.

fix: Resolve an issue where 'error' events triggered on the player during contrib-ads playback would not be recognized.

---

src/plugin.js
test/plugin.test.js

If the player is playing while the plugin is reinitialised, the playback monitor is stopped and will not restart until a play event.
On (re)initialisation, start the playback monitor immediately if playing.

fix: Restart timeout monitor if playing when reinitialised

---

scripts/test.rollup.config.js
src/plugin.js

This plugin is missing the standard `VERSION` property
Adds version to plugin and reinit function.

feat: add standard VERSION property

---

.yo-rc.json
package.json
scripts/rollup.config.js

See: 
* https://github.com/brightcove/videojs-errors/issues/124
* https://github.com/videojs/generator-videojs-plugin/pull/194
Closes #124 
Closes #125 
Closes #123 
Thanks to @chrisboustead for finding this!

fix: babel the es dist, by updating the generator

---

src/plugin.js
test/plugin.test.js

Listening to `progress` events is redundant, this plugin already monitors `timeupdate` for playhead progress. The error dialog does not pause on open so if playback resumes the error will be cleared by the playhead moving (https://github.com/videojs/video.js/blob/master/src/js/error-display.js#L61).
Remove the `progress` event listener so the timeout monitor does not reset.

fix: ignore progress events

---

src/plugin.js

Improves appearance of errors by emboldening a colon attached to bold text, and make styling the error display by adding a class to the div including the error code.
- Adds `vjs-errors-code` class
- Moves `:` inside adjacent `<b>`

feat: Add class to error code line and make colon bold

---

src/plugin.js

When using contrib-ads, if content stalls after a preroll we can get into a prolonged `contentResuming` state, during which player events are prefixed with `content`. If an error occurs during that window, we should still trigger the handler that populates the error modal.

fix: trigger onErrorHandler on 'contenterror' as well

---

src/plugin.js
test/plugin.test.js

This is a different approach to #197.
Background throttling can cause playback delays that will recover once the document becomes visible again, so it makes sense to handle foreground and background timeouts separately. This PR adds support for a `backgroundTimeout` option:
```js
// Note: these are the default values for each timeout
player.errors({
timeout: 45 * 1000,
// 5 minutes. Pretty arbitrary so we can discuss alternative default values
backgroundTimeout: 300 * 1000
});
// or after the plugin has been initialized:
player.errors.backgroundTimeout(Infinity);
```
Setting the value to `Infinity` disables background timeouts altogether.

feat: Add backgroundTimeout option

---

src/plugin.js

It is currently possible for multiple errors to generate div elements with duplicate `vjs-errors-dialog` ids.
Remove code to set `vjs-errors-dialog` on the generated div that wraps error content. The same string is already used to set a class on that element and the `vjs-errors-dialog` _id_ is not used for targeting in the plugin or the videojs org.

feat: Remove vjs-errors-dialog id

---

package.json
src/plugin.js

Prevents the following warning: 
`VIDEOJS: WARN: videojs.mergeOptions is deprecated and will be removed in 9.0; please use videojs.obj.merge instead.`
Also prevents a warning from lint-staged regarding `git add` (which was introduced in lint-staged v10)
`⚠ Some of your tasks use 'git add' command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.`
I can move the second change into another pull request if we want.

fix: prevent lint-staged git add warning and mergeOptions warning on Video.js@8

---

README.md
lang/ar.json
lang/cs.json
lang/de.json
lang/en.json
lang/ja.json
lang/ko.json
lang/zh-CN.json
package-lock.json
package.json
test/plugin.test.js

Update installed version of Video.js to 8.x, but maintain backward compatibility in `package.json` with versions 6 and newer.
- Update Video.js to 8.x
- Update tests to address failures introduced by Video.js 8 "retry on error" functionality. This is not a backward compatibility concern because the tests were using a more simplistic simulation of video playback previously.
- Remove remaining mentions of Flash from language files and README

chore(deps): use video.js 8.x by default, but maintain backward compatibility
